global_defs {
    enable_script_security
    script_user root
}

vrrp_script chk_backends {
    script "/check_backends.sh"
    interval 2
}

vrrp_instance VI_1 {
    state BACKUP
    interface eth0
    virtual_router_id 51
    priority 150
    advert_int 1

    virtual_ipaddress {
        172.20.0.100
    }

    track_script {
        chk_backends
    }
}